### ISSUE TITLE
GroovyFX TableView not working with Java8/JavaFX8

### ISSUE THREAD

**Issue by madmas** [groovyfx-project/groovyfx#13]
Creating a table view on a view with groovyFx does not work as the following exception is thrown:

```
[2015-08-25 19:25:27,570] [JavaFX Application Thread] ERROR griffon.core.GriffonExceptionHandler - Uncaught Exception
java.lang.NoClassDefFoundError: com/sun/javafx/accessible/providers/AccessibleProvider
	at groovyx.javafx.factory.EditingCallback.call(TableFactory.groovy:41)
	at javafx.scene.control.TableRow.createDefaultSkin(TableRow.java:212)
	at javafx.scene.control.Control.impl_processCSS(Control.java:859)
	at javafx.scene.Node.processCSS(Node.java:9056)
	at javafx.scene.Node.applyCss(Node.java:9153)
	at javafx.scene.Parent.layout(Parent.java:1079)
	at javafx.scene.Parent.layout(Parent.java:1085)
	at javafx.scene.Scene.doLayoutPass(Scene.java:552)
	at javafx.scene.Scene.preferredSize(Scene.java:1646)
	at javafx.scene.Scene.impl_preferredSize(Scene.java:1720)
	at javafx.stage.Window$9.invalidated(Window.java:846)
	at javafx.beans.property.BooleanPropertyBase.markInvalid(BooleanPropertyBase.java:109)
	at javafx.beans.property.BooleanPropertyBase.set(BooleanPropertyBase.java:144)
	at javafx.stage.Window.setShowing(Window.java:922)
	at javafx.stage.Window.show(Window.java:937)
	at javafx.stage.Stage.show(Stage.java:259)
Caused by: java.lang.ClassNotFoundException: com.sun.javafx.accessible.providers.AccessibleProvider
	... 16 more
```

**Comment by madmas** [comment]
After trying to verify this, it turns out that rebuilding groovyfx with the last Java 8 release (update 60) is sufficient to solve this.
So it seems like a release, rebuild based on a recent version of Java, is required ;-)

**Comment by alexramos74** [comment]
Hi, I'm having a similar problem, when I try to turn a tableColumn editable like this,

    tableColumn(text: "Value", property: "value", editable: true)

I get the following exception, with a very generic stack trace:

    org.codehaus.groovy.runtime.InvokerInvocationException: java.lang.NoClassDefFoundError: com/sun/javafx/accessible/providers/AccessibleProvider
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:97)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:233)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:272)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:909)
	at org.codehaus.groovy.runtime.InvokerHelper.invokePogoMethod(InvokerHelper.java:901)
	at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:884)
	at org.codehaus.groovy.runtime.InvokerHelper.invokeClosure(InvokerHelper.java:95)
	at groovyx.javafx.GroovyFX.start(GroovyFX.java:35)
	...

I can workaround this by adding the following Maven dependency to my project:

    <dependency>
       <groupId>net.java.openjfx.backport</groupId>
       <artifactId>openjfx-78-backport</artifactId>
       <version>1.8.0-ea-b96.1</version>
    </dependency>

Is this the correct approach or is there a new version of GroovyFX that doesn't use the AccessibleProvider interface at all?

My current development environment is:

* Eclipse Mars 4.5.0
* JDK 1.8_66
* Groovy compiler 2.3.10
* Maven project with dependency to GroovyFX 0.4.0

I apologize for asking user's questions on the developer section, but as Codehaus was closed I still don't know where your discussion lists are.

Many thanks.

**Comment by swalton00** [comment]
As I recall, the correction for this is in the checked in code, but there
is not yet a distribution for this. I think what I needed to do to fix this
was to clone  the repository, build it myself, and then do a maven install
to my local. That did resolve the issue though.

On Thu, Nov 12, 2015 at 12:23 PM, alexramos74 <notifications@github.com>
wrote:

> Hi, I'm having a similar problem, when I try to turn a tableColumn
> editable like this,
>
> tableColumn(text: "Value", property: "value", editable: true)
>
> I get the following exception, with a very generic stack trace:
>
> org.codehaus.groovy.runtime.InvokerInvocationException: java.lang.NoClassDefFoundError: com/sun/javafx/accessible/providers/AccessibleProvider
> at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:97)
>
>

-- 
Scott Walton

**Comment by alexramos74** [comment]
I did that, compiled locally and now it's working. Thanks.
