### ISSUE TITLE
FXMLDemoFromSceneBuilderFile fails calling scene.lookup

### ISSUE THREAD

**Issue by rich-coe** [groovyfx-project/groovyfx#57]
`Exception in Application start method
Caught: java.lang.RuntimeException: Exception in Application start method
java.lang.RuntimeException: Exception in Application start method
        at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:917)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$155(LauncherImpl.java:182)
Caused by: java.lang.NullPointerException: Cannot set property 'title' on null object
        at FXMLDemoFromSceneBuilderFile$_run_closure1.doCall(FXMLDemoFromSceneBuilderFile.groovy:30)
        at groovyx.javafx.GroovyFX.start(GroovyFX.java:40)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$162(LauncherImpl.java:863)
        at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$175(PlatformImpl.java:326)
        at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
        at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
        at com.sun.glass.ui.gtk.GtkApplication.lambda$null$49(GtkApplication.java:139)
`

According to https://stackoverflow.com/questions/32773847/scene-lookup-returns-null-if-i-search-my-vbox lookups ''are not very robust"

**Comment by rich-coe** [comment]
pull request #58 fixes this issue
